#' @keywords internal
"_PACKAGE"

#' @import rlang
#'
## usethis namespace: start

#' @importFrom arrow open_dataset
#' @importFrom cli cli_abort
#' @importFrom cli cli_inform
#' @importFrom cli cli_warn
#' @importFrom DARAutils formatter_cli
#' @importFrom DARAutils inheriting_merge
#' @importFrom DARAutils layout_generator_subject
#' @importFrom DARAutils local_logger_sink
#' @importFrom DBI dbConnect
#' @importFrom DBI dbDisconnect
#' @importFrom DBI dbGetQuery
#' @importFrom dbplyr in_catalog
#' @importFrom dbplyr in_schema
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr as_tibble
#' @importFrom dplyr between
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr filter
#' @importFrom dplyr if_else
#' @importFrom dplyr intersect
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n_distinct
#' @importFrom dplyr pull
#' @importFrom dplyr rename_with
#' @importFrom dplyr select
#' @importFrom dplyr setdiff
#' @importFrom dplyr summarise
#' @importFrom dplyr tbl
#' @importFrom fs dir_create
#' @importFrom fs file_exists
#' @importFrom fs path
#' @importFrom fs path_ext
#' @importFrom ggplot2 ggsave
#' @importFrom igraph graph_from_data_frame
#' @importFrom igraph neighborhood
#' @importFrom igraph simplify
#' @importFrom igraph subgraph
#' @importFrom igraph vertex_attr
#' @importFrom igraph vertex_attr<-
#' @importFrom logger appender_tee
#' @importFrom logger layout_simple
#' @importFrom logger log_appender
#' @importFrom logger log_error
#' @importFrom logger log_errors
#' @importFrom logger log_formatter
#' @importFrom logger log_info
#' @importFrom logger log_layout
#' @importFrom logger log_messages
#' @importFrom logger log_namespaces
#' @importFrom logger log_success
#' @importFrom logger log_warn
#' @importFrom logger log_warnings
#' @importFrom lubridate day
#' @importFrom lubridate isoweek
#' @importFrom lubridate isoyear
#' @importFrom lubridate month
#' @importFrom lubridate now
#' @importFrom lubridate seconds
#' @importFrom lubridate wday
#' @importFrom lubridate year
#' @importFrom lubridate ymd
#' @importFrom lubridate ymd_hm
#' @importFrom purrr discard
#' @importFrom purrr keep
#' @importFrom purrr map
#' @importFrom purrr map_if
#' @importFrom purrr map_lgl
#' @importFrom purrr map2_chr
#' @importFrom purrr walk
#' @importFrom readr read_file
#' @importFrom readr read_rds
#' @importFrom readr write_csv2
#' @importFrom readxl excel_sheets
#' @importFrom readxl read_excel
#' @importFrom rmarkdown render
#' @importFrom rstudioapi getSourceEditorContext
#' @importFrom stringr str_c
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_glue
#' @importFrom stringr str_remove
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split_i
#' @importFrom stringr str_subset
#' @importFrom stringr str_to_lower
#' @importFrom svglite svglite
#' @importFrom tibble tibble
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyr unnest_longer
#' @importFrom tidyselect all_of
#' @importFrom tidyselect ends_with
#' @importFrom tidyselect everything
#' @importFrom utils find
#' @importFrom utils hasName
#' @importFrom vctrs vec_rbind
#' @importFrom visNetwork toVisNetworkData
#' @importFrom visNetwork visEdges
#' @importFrom visNetwork visHierarchicalLayout
#' @importFrom visNetwork visNetwork
#' @importFrom visNetwork visOptions
#' @importFrom vroom vroom
#' @importFrom withr defer
#' @importFrom writexl write_xlsx
#' @importFrom yaml read_yaml
## usethis namespace: end
NULL
