#' Setup the R environment for creation of objects
#'
#' @description setup_environment() is run at the top of an object creation
#'   script and ensures the dependencies are loaded. If this function is run
#'   interactively() by the user at the top of an object script, then,
#'   additionally, setup_environment() deduces which object is worked on and
#'   detemines the object_name.
#'
#' @param cur_env Environment. The environment from which setup_environment() is
#'   called. object_name (only if cur_env == .GlobalEnv) and the list of
#'   imported objects will be attached to this environment.
#' @param prepare_script Character. Location of the script that prepares R by
#'   importing packages etc. Default ="scripts/00_prepare/prepare.R"
#' @param config_checks run the config checks for this object. Default is TRUE.
#' @param p_e pipeline environment.
#' @return invisible(NULL)
#'
#' @examples
#' \dontrun{
#' setup_environment(environment())
#' ### ### ### DO NOT EDIT ABOVE THIS LINE! ### ### ###
#' # (place the above at the top of a new object script)
#' }
#'
#' @export
setup_environment <- function(cur_env,
                              prepare_script = "scripts/00_prepare/prepare.R",
                              config_checks = TRUE,
                              p_e = pipeline_env) {
  # NB it is not possible to set cur_env = environment() as default since the
  # expression would be evaluated from within the function resulting in a
  # different value when determined outside the function. in other words:
  # setup_environment(environment()) != setup_environment()
  log_info("Starting {.code setup_environment()}")

  # Determine object_name (dev-mode) ----------------------------------------
  if (interactive() && identical(cur_env, .GlobalEnv)) {
    # "dev-mode": in this mode the r script is directly sourced
    source(prepare_script)
    # attach object_name to the current environment (in this case global env)
    cur_file <- getSourceEditorContext()$path
    cur_env$object_name <- cur_file |>
      basename() |>
      str_remove(".R$")
    log_info("{.strong Running generate script in interactive mode}")
    log_info(
      "{.arg object_name} is set to {.val {cur_env$object_name}} ",
      "(It was derived from the filename {.file {cur_file}})"
    )
  } else if (exists("curr_object", envir = p_e)) {
    # pipeline_ function-style
    object_name <- get("curr_object", envir = p_e)
  }

  # import data (all modes) -------------------------------------------------
  # all upstream objects (excluding object_name itself) that may have to be
  # generated by pipeline_run(). Will effectively only run in dev-mode
  # because the pipeline_run() call in scripts/02_objects/... will only run
  # object creation in the correct order.
  all_upstream_objects <- setdiff(grab_target_list(objects = object_name, p_e = p_e), object_name)
  if (!all(all_upstream_objects %in% names(.GlobalEnv)) || any(all_upstream_objects %in% p_e$refresh)) {
    log_info("{.code setup_environment()} for {.val {object_name}} requires upstream objects to be created.")
    log_info("Running {.code pipeline_run()} in preparation...")
    pipeline_run(objects = all_upstream_objects, p_e = p_e)
  }
  # import all objects/data/other needed for object_name
  pipeline_import_for(object_name, p_e = p_e)

  if (config_checks) {
    # check if all dependencies are used in object generation, otherwise throw warning
    check_usage_dependencies(object_name, p_e = p_e)
    # check if dependencies are used but not mentioned in object_relations, otherwise throw warning
    check_dependencies_not_listed(object_name, p_e = p_e)
  }

  log_info("Finished {.code setup_environment()}")
  return(invisible(NULL))
}


#' Check usage dependencies
#'
#' From the initialized pipeline environment, `check_usage_dependencies` checks whether
#' the dependencies specified in the configuration files for this object are being
#' used in the R object script. The location of the R script is retrieved from the
#' pipeline environment object `p_e`. The usage check is done by performing a string
#' search within the R script file with filename `object_name`.
#'
#' @param object_name Character. The name of the object.
#' @param p_e pipeline environment
#'
#' @returns invisible NULL
#'
#' @keywords internal
#' @md
#'
check_usage_dependencies <- function(object_name, p_e = pipeline_env, test_mode = FALSE) {
  depends_on <- get_depends_on_list(object_name)

  # if there are no dependencies, don't continue the check (invisible early return)
  if (is.null(depends_on)) {
    return(invisible(NULL))
  }


  if (test_mode) {
    print("testmode added")
    script_loc <- testthat::test_path(p_e$object_param_list[[object_name]]$generate_script)
  } else {
    script_loc <- p_e$object_param_list[[object_name]]$generate_script
  }

  script_str <- read_file(script_loc)

  for (dep in depends_on){
    dep_exact <- paste0("\\b", dep, "\\b")
    if (!str_detect(string = script_str, pattern = dep_exact)) {
      cli_warn(c(
        "!" = "{.arg object_name} {.val {object_name}} depends on {.val {dep}}, as stated in the
        {.file config/base/object_relations.yaml} file, but it is never used in the object generate script:
        {.file {script_loc}}",
        "i" = "Can you remove {.val {dep}} as a dependency of {.val {object_name}} from the
        {.file config/base/object_relations.yaml} file?"
      ))
    }
  }
}

#' Check dependencies used and not mentioned in object_relations
#'
#' From the initialized pipeline environment, `check_dependencies_not_listed` to check
#' whether any of the dependencies specified in the config files are used but not listed in `object_relations.yaml`
#' config. The location of the R script
#' is retrieved from the pipeline environment object `p_e`. The usage check is done by performing a string
#' search  within the R script file.
#' This is necessary because dependency relations may be missing, but the pipeline
#' can still succeed if the dependency is referenced in an object that was generated earlier.
#'
#' @param object_name Character. The name of the object.
#' @param p_e pipeline environment
#'
#' @returns invisible NULL
#'
#' @keywords internal
#' @md
#'
check_dependencies_not_listed <- function(object_name, p_e = pipeline_env, test_mode = FALSE) {
  depends_on <- get_depends_on_list(object_name)
  # get names of all unique data assets mentioned in the config relations yaml
  all_data_assets <- grab_object_table() |>
    pull(.data$data_asset_name)
  # get the data assets mentioned in the config without those mentioned in the
  # depends_on and the object_name of the current object
  diff_data_assets <- setdiff(all_data_assets, c(object_name, depends_on))

  script_loc <- p_e$object_param_list[[object_name]]$generate_script

  if (test_mode) {
    script_str <- read_file(testthat::test_path(script_loc))
  } else {
    script_str <- read_file(script_loc)
  }
  for (data_asset in diff_data_assets) {
    data_asset_exact <- paste0("\\b", data_asset, "\\b")
    if (str_detect(string = remove_comments(script_str), pattern = data_asset_exact)) {
      cli_warn(
        c(
          "!" = "{.arg object_name} uses {.val {data_asset}} in the object generate script:{.file {script_loc}}
        but this is not stated in the {.file config/base/object_relations.yaml} file.",
          "i" = "Can you add {.val {data_asset}} as a dependency of {.val {object_name}} in the
        {.file config/base/object_relations.yaml} file or
        remove {.val {data_asset}} (only if unnecessary) from the generate script:{.file {script_loc}}?"
        )
      )
    }
  }
}

#' Get all dependencies for checks on config
#'
#' @description
#' This function gets all dependencies as listed in object table
#'
#' @param object_name Character.
#'
#' @returns An array of dependencies for the config dependency check functions.
#'
#' @keywords internal
#' @md
#'
get_depends_on_list <- function(object_name) {
  grab_object_table() |>
    filter(.data$data_asset_name == object_name) |>
    pull(.data$depends_on) |>
    unlist() |>
    unique()
}
